### ISSUE TITLE
TLV493D.cpp Line 159 is incorrect.

### ISSUE THREAD

**Issue by lloydsargent42** [IRNAS/TLV493D-3D-Magnetic-Sensor-Arduino-Library#3]
The code appears as follows:

    // Read Register 9H 4:0 -> Write Register 3H 4:0 (Mod2).
    m_wbuffer[3] = m_rbuffer[9] & B00001111;

The comment is actually correct, bits 4:0 (B00011111) should be copied. Thus the code SHOULD look like the following:

    // Read Register 9H 4:0 -> Write Register 3H 4:0 (Mod2).
    m_wbuffer[3] = m_rbuffer[9] & B00011111;

Cheers!

**Comment by VojislavM** [comment]
Thank you, I have changed this.
