### ISSUE TITLE
Some key information on sensor which is doubtful in your implementation

### ISSUE THREAD

**Issue by ujur007** [IRNAS/TLV493D-3D-Magnetic-Sensor-Arduino-Library#5]
I don't know but hope that the library is for TLV493D-A1B6 sensor, There is some information in the following doc.
The write reg. are using values only from read reg 7 and 9... in your code it is different.!!

Also in temp measurement as per the datasheet it should be LSB-340 and in your case it is 320??

[https://www.infineon.com/dgdl/Infineon-TLV493D-A1B6_3DMagnetic-UM-v01_03-EN.pdf?fileId=5546d46261d5e6820161e75721903ddd](url)

**Comment by VojislavM** [comment]
Hi @ujur007 
You might be right about our driver, but be aware that this code was developed for our system so it does not have all sensor features implemented. The one that are implemented **work well for us**. Never the less if you are writing code and need a library for this sensor I recommend you to use official Infinion Arduino lib which you can find on the link:
https://github.com/Infineon/TLV493D-A1B6-3DMagnetic-Sensor
